apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../default
- ../../network-policy
- tls_clusterrole.yaml
- tls_clusterrolebinding.yaml

configurations:
- kustomizeconfig.yaml

patches:
- path: metrics_service_patch.yaml
  target:
    kind: Service
    name: controller-manager-metrics-service
- path: metrics_cert_manager_patch.yaml
  target:
    kind: Deployment
